version: '3.7'
services:
  api:
    container_name: api
    build: ./api/
    ports:
      - "8080:8080"
    environment:
      DYNAMO_ENDPOINT: dynamodb-demo:8000
      AWS_ACCESS_KEY_ID: idol-cheki
      AWS_SECRET_ACCESS_KEY: idol-cheki
      AWS_DEFAULT_REGION: ap-northeast-1
      TABLE_NAME: idol-groups
    depends_on:
      - dynamodb-demo

  dynamodb-demo:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-demo
    ports:
      - "8011:8000"
    volumes:
      - dynamodb:/home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
    environment:
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: idol-cheki
      AWS_SECRET_ACCESS_KEY: idol-cheki
 
  dynamodb-admin-demo:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin-demo
    ports:
      - "8013:8001"
    environment:
      DYNAMO_ENDPOINT: dynamodb-demo:8000
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: idol-cheki
      AWS_SECRET_ACCESS_KEY: idol-cheki
    depends_on:
      - dynamodb-demo

volumes:
  dynamodb:
    driver: local
