version: '3.7'
services:
  api:
    container_name: api
    build: ./api/
    ports:
      - "8080:8080"
    environment:
      DYNAMO_ENDPOINT: dynamodb-dev:8000
      AWS_ACCESS_KEY_ID: idol-cheki
      AWS_SECRET_ACCESS_KEY: idol-cheki
      AWS_DEFAULT_REGION: ap-northeast-1
      TABLE_NAME: idol-groups
    depends_on:
      - dynamodb-dev
